jobs:
  build-debug-apk:
    continue-on-error: true
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        submodules: true
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 21
    - continue-on-error: true
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-encryption-key: Da25KUVSE5jbGds2zXmfXw==
        gradle-home-cache-cleanup: true
    - continue-on-error: true
      if: github.repository_owner == 'LawnchairLauncher'
      name: Write sign info
      run: "if [ ! -z \"${{ secrets.KEYSTORE }}\" ]; then\n  echo storePassword='${{\
        \ secrets.KEYSTORE_PASSWORD }}' >> keystore.properties\n  echo keyAlias='${{\
        \ secrets.KEY_ALIAS }}' >> keystore.properties\n  echo keyPassword='${{ secrets.KEY_PASSWORD\
        \ }}' >> keystore.properties\n  echo storeFile='${{ github.workspace }}/key.jks'\
        \ >> keystore.properties\n  echo ${{ secrets.KEYSTORE }} | base64 --decode\
        \ > ${{ github.workspace }}/key.jks\nfi\n"
    - continue-on-error: true
      name: Build debug APK
      run: ./gradlew assembleLawnWithQuickstepGithubDebug assembleLawnWithQuickstepMarketDebug
    - continue-on-error: true
      name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Debug APK
        path: build/outputs/apk/**/*.apk
  check-style:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        submodules: true
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 21
    - continue-on-error: true
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true
    - continue-on-error: true
      run: ./gradlew spotlessCheck
  crowdin-auto-merge:
    if: github.event.pull_request.user.login == 'lawnchair-bot' && github.event.pull_request.title
      == 'New Crowdin translations by Github Action'
    needs: build-debug-apk
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.LAWNCHAIR_BOT_TOKEN }}
        PR_URL: ${{ github.event.pull_request.html_url }}
      run: 'gh pr comment $PR_URL --body "No issues found, auto-merging the Crowdin
        pull request."

        gh pr merge $PR_URL --auto --squash --delete-branch

        '
  nightly-release:
    if: github.repository_owner == 'LawnchairLauncher' && github.event_name == 'push'
      && github.ref == 'refs/heads/14-dev'
    needs: build-debug-apk
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/download-artifact@v4
    - continue-on-error: true
      name: Export APK_NAME for later use
      run: echo "APK_NAME=Lawnchair.Debug.${{ github.ref_name }}.Nightly-CI_${{ github.run_number
        }}-$(echo ${{ github.sha }} | cut -c1-7).apk" >> $GITHUB_ENV
    - continue-on-error: true
      name: Rename .apk file
      run: mv "./Debug APK/lawnWithQuickstepGithub/debug/"*.apk "./$APK_NAME"
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Delete release if exist then create release
      run: 'gh release view "nightly" && gh release delete "nightly" -y --cleanup-tag

        gh release create "nightly" "./$APK_NAME" -p -t "Lawnchair Nightly" --generate-notes

        '
  send-notifications:
    if: github.repository_owner == 'LawnchairLauncher'
    needs: build-debug-apk
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - continue-on-error: true
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - continue-on-error: true
      name: Install Python packages
      run: 'python -m pip install --upgrade pip

        pip install gitpython requests

        '
    - continue-on-error: true
      name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: Debug APK
        path: artifacts/debug-apk
    - continue-on-error: true
      env:
        ACTION: internal_notifications
        ARTIFACT_DIRECTORY: artifacts/debug-apk
        GITHUB_EVENT_BEFORE: ${{ github.event.before }}
        GITHUB_REF: ${{ github.ref }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_CI_BOT_TOKEN }}
        TELEGRAM_CI_CHANNEL_ID: ${{ secrets.TELEGRAM_CI_CHANNEL_ID }}
        TELEGRAM_TEAM_GROUP_ID: ${{ secrets.NOTIFY_CHANNEL_ID }}
      name: Send notifications
      run: python ci.py
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
