jobs:
  stale:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v9
      with:
        close-issue-message: This issue was closed because it has been stale for 7
          days with no activity.
        close-issue-reason: not_planned
        close-pr-message: This PR was closed because it has been stale for 14 days
          with no activity.
        days-before-issue-close: 7
        days-before-issue-stale: 90
        days-before-pr-close: 14
        days-before-pr-stale: 60
        exempt-all-assignees: true
        exempt-all-milestones: true
        operations-per-run: 1000
        stale-issue-message: This issue is stale because it has been open for 90 days
          with no activity. Remove stale label or comment or this will be closed in
          7 days.
        stale-pr-message: This PR is stale because it has been open for 60 days with
          no activity. Remove stale label or comment or this will be closed in 14
          days.
name: Close stale issues and PRs
on:
  repository_dispatch:
    types: trigger-ga___close_stale_issues.yml
