jobs:
  build-release-apk:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        submodules: true
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 21
    - continue-on-error: true
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true
    - continue-on-error: true
      id: sign-release-apk
      if: github.repository_owner == 'LawnchairLauncher'
      name: Write sign info
      run: "if [ ! -z \"${{ secrets.KEYSTORE }}\" ]; then\n  echo storePassword='${{\
        \ secrets.KEYSTORE_PASSWORD }}' >> keystore.properties\n  echo keyAlias='${{\
        \ secrets.KEY_ALIAS }}' >> keystore.properties\n  echo keyPassword='${{ secrets.KEY_PASSWORD\
        \ }}' >> keystore.properties\n  echo storeFile='${{ github.workspace }}/key.jks'\
        \ >> keystore.properties\n  echo ${{ secrets.KEYSTORE }} | base64 --decode\
        \ > ${{ github.workspace }}/key.jks\nfi\n"
    - continue-on-error: true
      name: Build release APK
      run: ./gradlew assembleLawnWithQuickstepGithubRelease
    - continue-on-error: true
      name: Rename artifact
      run: mv build/outputs/apk/**/**/*.apk "${{ github.event.inputs.artifactName
        }}"
    - continue-on-error: true
      name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Release APK
        path: ${{ github.event.inputs.artifactName }}
  publish-github-release:
    needs: build-release-apk
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: Release APK
        path: artifacts/release-apk
    - continue-on-error: true
      name: Publish GitHub release
      uses: softprops/action-gh-release@v2
      with:
        body_path: ${{ github.workspace }}/GITHUB_CHANGELOG.md
        draft: true
        files: artifacts/release-apk/${{ github.event.inputs.artifactName }}
        name: ${{ github.event.inputs.releaseName }}
        prerelease: ${{ github.events.inputs.prerelease }}
        tag_name: ${{ github.event.inputs.tagName }}
  publish-telegram-update-post:
    needs: build-release-apk
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: Release APK
        path: artifacts/release-apk
    - continue-on-error: true
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - continue-on-error: true
      name: Install Python packages
      run: 'python -m pip install --upgrade pip

        pip install gitpython requests

        '
    - continue-on-error: true
      env:
        ACTION: update_announcement
        ARTIFACT_DIRECTORY: artifacts/release-apk
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_CI_BOT_TOKEN }}
        TELEGRAM_NEWS_CHANNEL_ID: ${{ secrets.TELEGRAM_NEWS_CHANNEL_ID }}
      name: Publish Telegram update post
      run: python ci.py
name: Release update
on:
  repository_dispatch:
    types: trigger-ga___release_update.yml
